import { STAGE_LABELS, TERRAIN_TYPES, PROGRAM_TYPES } from './data.js';
import {
  createUniverse,currentAbility,dateFromDay,dayOfYear,directorById,directorHallScore,eventById,eventCategory,hallOfFame,hallScore,
  riderById,simulateSeason,simulateWeeks,teamById,teamHallScore,topRiders,upgradeUniverse
} from './engine.js';
import { deleteUniverse,listUniverses,loadUniverse,saveUniverse } from './storage.js';
import { countryFlag,esc,formatNumber,titleCase } from './utils.js';

const app=typeof document!=='undefined'?document.querySelector('#imperative-app'):null;
let state=null,slot=null,route='results',modal=null,busy=false,toastTimer=null,selectedEventId=null,selectedRaceId=null,almanacTab='riders',magazineTab='preseason',statsEntity='riders',statsMetric='raceWins',statsTier='all',statsScope='season';

if(app)init();
async function init(){renderLoading();try{renderSaveScreen(await listUniverses());}catch(error){console.error(error);app.innerHTML='<div class="loading">IndexedDB could not be opened.</div>';}}
function renderLoading(){app.innerHTML='<div class="loading">Opening the cycling archive…</div>';}
function toast(message){document.querySelector('.toast')?.remove();const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.append(node);clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.remove(),2800);}
async function persist(){if(slot&&state)state=await saveUniverse(slot,state);}
function renderSaveScreen(rows){const bySlot=new Map(rows.map(row=>[row.slot,row]));app.innerHTML=`<main class="save-screen"><section class="save-paper"><header class="save-title"><div class="eyebrow">The international road cycling archive</div><h1>Peloton Chronicle</h1><p>Simulate by week. Follow every career. Preserve every era.</p></header><div class="save-slots">${[1,2,3].map(n=>saveSlot(n,bySlot.get(n))).join('')}</div></section></main>`;}
function saveSlot(number,row){return `<article class="save-slot ${row?'':'empty'}"><div><div class="eyebrow">Archive drawer ${number}</div><h3>${row?esc(row.name):'Empty Chronicle'}</h3>${row?`<p class="muted">Season ${row.year} · Week ${Math.ceil((row.currentDay||1)/7)}</p><small class="muted">Updated ${new Date(row.updatedAt).toLocaleString()}</small>`:'<p class="muted">Create a procedural modern cycling world beginning in 2026.</p>'}</div><div class="top-actions">${row?`<button class="btn" data-load-slot="${number}">Open</button><button class="btn danger" data-delete-slot="${number}">Delete</button>`:`<button class="btn gold" data-new-slot="${number}">Create universe</button>`}</div></article>`;}
async function openSlot(number){busy=true;renderLoading();slot=number;state=upgradeUniverse(await loadUniverse(number));route='results';selectedEventId=latestResult()?.eventId||state.events[0]?.id;busy=false;render();}
async function newSlot(number){const name=window.prompt('Name this cycling universe','Main Chronicle')||'Main Chronicle';slot=number;state=createUniverse({name,seed:Date.now()%2147483647});await persist();route='results';selectedEventId=state.events[0]?.id;render();}

function shell(content){
  const date=dateFromDay(state.year,state.currentDay||1),next=state.events[state.eventIndex],week=Math.ceil((state.currentDay||1)/7);
  return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-kicker">Cycling history since ${state.archives[0]?.year||state.year}</div><h1>Peloton<br/>Chronicle</h1><p>${esc(state.name)}</p></div><nav class="nav">
  ${navButton('results','Results','▤')}${navButton('calendar','Calendar','▦')}${navButton('races','Races','⚑')}
  <div class="nav-section">The peloton</div>${navButton('riders','Riders','●')}${navButton('teams','Teams','◆')}${navButton('directors','Race Directors','✦')}${navButton('transfers','Market','⇄')}
  <div class="nav-section">History & records</div>${navButton('stats','Statistics','▥')}${navButton('magazine','Le Grand Braquet','✒')}${navButton('almanac','Almanac','▣')}${navButton('hall','Hall of Fame','♜')}
  <div class="nav-section">Universe</div>${navButton('settings','Save & Settings','⚙')}
  </nav><div class="sidebar-footer">WorldTour and ProSeries in full; U23 and continental cycling feed the professional market.</div></aside>
  <main class="main"><header class="topbar"><div class="season-date"><button class="btn secondary menu-btn" data-menu>☰</button><strong>${state.year}</strong><span>Week ${week} · ${date.label}${next?` · Next: ${esc(next.name)}`:' · Season review'}</span></div><div class="top-actions simulation-actions"><button class="btn secondary" data-action="simulate-1">+ 1 week</button><button class="btn secondary" data-action="simulate-4">+ 4 weeks</button><button class="btn gold" data-action="simulate-season">End of year</button></div></header><div class="content">${content}</div></main></div>${modal?renderModal():''}`;
}
function navButton(id,label,icon){return `<button class="${route===id?'active':''}" data-route="${id}"><span>${icon}</span>${label}</button>`;}
function pageHead(kicker,title,copy,extra=''){return `<header class="page-head"><div><div class="eyebrow">${kicker}</div><h2>${title}</h2><p>${copy}</p></div>${extra||`<div class="date-stamp">Season ${state.year}</div>`}</header>`;}
function pageFor(id){const pages={results:resultsPage,calendar:calendarPage,races:racesPage,'race-detail':raceDetailPage,riders:ridersPage,teams:teamsPage,directors:directorsPage,transfers:transfersPage,stats:statsPage,magazine:magazinePage,almanac:almanacPage,hall:hallPage,settings:settingsPage};return pages[id]||resultsPage;}
function render(){if(!state)return;app.innerHTML=shell(pageFor(route)());}
export function renderPageForTest(universe,page='results'){state=upgradeUniverse(universe);route=page;selectedEventId=selectedEventId||state.events[0]?.id;selectedRaceId=selectedRaceId||state.events[0]?.id;modal=null;return shell(pageFor(page)());}

function latestResult(){return state?.eventResults?.at(-1)||null;}
function currentResult(eventId){return state.eventResults.find(result=>result.eventId===eventId&&result.year===state.year);}
function teamName(id){if(!id)return'—';return teamById(state,id)?.name||id.replace(/^u23-nation-|^nation-/,'');}
function directorName(id){return directorById(state,id)?.name||'Vacant';}
function monthName(month){return ['','January','February','March','April','May','June','July','August','September','October','November','December'][month];}
function formatGap(seconds){const minutes=Math.floor(seconds/60),rest=seconds%60;return minutes?`${minutes}′ ${String(rest).padStart(2,'0')}″`:`${rest}″`;}
function typeLabel(event){return {'grand-tour':'Grand Tour',monument:'Monument','stage-race':'Stage race',classic:'Classic',championship:'Championship'}[eventCategory(event)];}
function tierLabel(tier){return tier==='worldtour'?'WorldTour':tier==='proseries'?'ProSeries':tier==='u23'?'U23':tier==='continental'?'Continental':'National';}
function statValue(book,metric,tier='all'){if(!book)return 0;return tier==='all'?(book[metric]||0):(book.byTier?.[tier]?.[metric]||0);}

function seasonLeaders(){
  const active=state.riders.filter(r=>!r.retired),teams=state.teams.filter(t=>t.status==='active');
  return {wins:[...active].sort((a,b)=>b.currentSeason.raceWins-a.currentSeason.raceWins||b.currentSeason.uciPoints-a.currentSeason.uciPoints)[0],stages:[...active].sort((a,b)=>b.currentSeason.stageWins-a.currentSeason.stageWins)[0],points:[...active].sort((a,b)=>b.currentSeason.uciPoints-a.currentSeason.uciPoints)[0],team:[...teams].sort((a,b)=>b.currentSeason.uciPoints-a.currentSeason.uciPoints)[0]};
}
function resultsPage(){
  const leaders=seasonLeaders();if(!selectedEventId)selectedEventId=latestResult()?.eventId||state.events[0]?.id;const selected=eventById(state,selectedEventId)||state.events[0],result=currentResult(selected?.id);
  return `${pageHead('The weekly race desk','Results','Move the entire world forward by week. Every race occurring in that period resolves automatically; this desk lets you browse the current season without clicking through the calendar.')}
  <div class="grid cols-4 season-strip"><article class="card kpi"><span>Race wins leader</span><strong>${leaders.wins?.currentSeason.raceWins||0}</strong><small>${leaders.wins?`${countryFlag(leaders.wins.nationality)} ${esc(leaders.wins.name)}`:'No winner yet'}</small></article><article class="card kpi"><span>Stage wins leader</span><strong>${leaders.stages?.currentSeason.stageWins||0}</strong><small>${leaders.stages?`${countryFlag(leaders.stages.nationality)} ${esc(leaders.stages.name)}`:'No stages yet'}</small></article><article class="card kpi"><span>World points</span><strong>${formatNumber(leaders.points?.currentSeason.uciPoints||0)}</strong><small>${leaders.points?esc(leaders.points.name):'Season not started'}</small></article><article class="card kpi"><span>Leading team</span><strong>${leaders.team?.currentSeason.raceWins||0}</strong><small>${leaders.team?`${esc(leaders.team.name)} race wins`:'No team yet'}</small></article></div>
  <div class="results-browser"><section class="race-index card"><div class="filters compact"><select id="results-tier"><option value="all">All tiers</option>${tierOptions()}</select><select id="results-type"><option value="all">All race types</option>${typeOptions()}</select><input id="results-search" placeholder="Search race…"></div><div class="race-index-list" id="results-list">${state.events.map(event=>resultIndexRow(event,selected?.id)).join('')}</div></section><section class="result-desk">${result?resultView(result,selected,true):upcomingRaceView(selected)}</section></div>
  <div class="section-title"><h3>Season form table</h3><a data-route="stats">Open full statistics</a></div>${leaderTable(state.riders.filter(r=>!r.retired).sort((a,b)=>b.currentSeason.uciPoints-a.currentSeason.uciPoints).slice(0,12),'current')}`;
}
function resultIndexRow(event,selectedId){const result=currentResult(event.id),status=result?`<span class="result-winner">${countryFlag(riderById(state,result.winnerId)?.nationality)} ${esc(result.winnerName)}</span>`:dayOfYear(state.year,event.month,event.day)<state.currentDay?'<span class="muted">No edition</span>':'<span class="muted">Upcoming</span>';return `<button class="race-index-row ${event.id===selectedId?'selected':''}" data-select-result="${event.id}" data-tier="${event.tier}" data-type="${eventCategory(event)}" data-search="${esc(event.name.toLowerCase())}"><span class="race-date">${monthName(event.month).slice(0,3)} ${event.day}</span><span><strong>${countryFlag(event.country)} ${esc(event.name)}</strong><small>${tierLabel(event.tier)} · ${typeLabel(event)}</small>${status}</span><span class="prestige-number">${event.prestige}</span></button>`;}
function upcomingRaceView(event){if(!event)return'';const favorites=eventFavorites(event,6);return `<article class="race-poster ${eventCategory(event)}"><div class="poster-meta">${monthName(event.month)} ${event.day} · ${tierLabel(event.tier)}</div><h3>${countryFlag(event.country)} ${esc(event.name)}</h3><div class="poster-number">${event.prestige}</div><p>${event.stageProfiles.length===1?STAGE_LABELS[event.stageProfiles[0]]:`${event.stageProfiles.length} stages`} · ${typeLabel(event)}</p><div class="section-title light"><h3>Projected favorites</h3></div>${favorites.map((r,i)=>riderLine(r,i+1)).join('')||'<p>No projected start list yet.</p>'}<button class="btn paper" data-open-race="${event.id}">Go to race details</button></article>`;}
function resultView(result,event,showRaceButton=false){
  return `<section class="result-sheet"><div class="race-result-hero ${eventCategory(event)}"><div><div class="eyebrow">Official ${state.year} result · ${tierLabel(result.tier)}</div><h3>${esc(result.eventName)}</h3><p>${countryFlag(riderById(state,result.winnerId)?.nationality)} <button class="entity-link inverted" data-open-rider="${result.winnerId}">${esc(result.winnerName)}</button> · ${esc(teamName(result.winnerTeamId))}</p></div><div class="winner-seal"><span>Winner</span><strong>${result.classification[0]?.rank||1}</strong></div></div>
  <div class="result-columns"><article class="card"><div class="section-title flush"><h3>Final classification</h3><span>Top 10</span></div>${classificationTable(result)}</article><article class="card"><div class="section-title flush"><h3>${result.stages.length>1?'Stages':'Race profile'}</h3><span>${result.stages.length} day${result.stages.length===1?'':'s'}</span></div>${stageList(result)}${result.stages.length>1?jerseysView(result):''}${showRaceButton?`<button class="btn gold full" data-open-race="${event.id}">Go to race details & history</button>`:''}</article></div></section>`;
}
function classificationTable(result){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Rider</th><th>Team</th><th>Gap</th></tr></thead><tbody>${result.classification.slice(0,10).map(row=>`<tr><td class="rank">${row.rank}</td><td><button class="entity-link" data-open-rider="${row.riderId}">${countryFlag(riderById(state,row.riderId)?.nationality)} ${esc(row.name)}</button></td><td>${esc(teamName(row.teamId))}</td><td>${row.rank===1?'Winner':`+${formatGap(row.gap)}`}</td></tr>`).join('')}</tbody></table></div>`;}
function stageList(result){return `<div class="stage-list">${result.stages.map(stage=>`<div class="stage-row"><span class="stage-no">${result.stages.length===1?'Race':`Stage ${stage.number}`}</span><span class="profile-mark ${stage.profile}">${STAGE_LABELS[stage.profile]}</span><button class="entity-link" data-open-rider="${stage.winnerId}">${countryFlag(riderById(state,stage.winnerId)?.nationality)} ${esc(stage.winnerName)}</button><small>${esc(teamName(stage.teamId))}</small></div>`).join('')}</div>`;}
function jerseysView(result){return `<div class="jersey-grid">${jerseyCard('General',result.winnerId,'yellow')}${jerseyCard('Points',result.jerseys.points,'green')}${jerseyCard('Mountains',result.jerseys.mountains,'polka')}${jerseyCard('Young rider',result.jerseys.young,'white')}</div>`;}
function jerseyCard(label,id,color){const rider=riderById(state,id);return rider?`<button class="jersey-card ${color}" data-open-rider="${id}"><span class="jersey-icon"></span><small>${label}</small><strong>${esc(rider.name)}</strong></button>`:'';}
function riderLine(rider,rank){return `<button class="entity-link rider-line" data-open-rider="${rider.id}"><span class="rank">${rank}</span><span>${countryFlag(rider.nationality)} <strong>${esc(rider.name)}</strong><small>${esc(teamName(rider.teamId))} · ${titleCase(rider.program)}</small></span><b>${Math.round(currentAbility(rider))}</b></button>`;}
function leaderTable(riders,mode='career'){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Rider</th><th>Team</th><th>Tier</th><th>Points</th><th>Races</th><th>Stages</th></tr></thead><tbody>${riders.map((r,i)=>{const b=mode==='current'?r.currentSeason:r.career;return `<tr><td class="rank">${i+1}</td><td><button class="entity-link" data-open-rider="${r.id}">${countryFlag(r.nationality)} ${esc(r.name)}</button></td><td>${esc(teamName(r.teamId))}</td><td>${tierLabel(r.tier)}</td><td>${formatNumber(b.uciPoints)}</td><td>${b.raceWins}</td><td>${b.stageWins}</td></tr>`;}).join('')}</tbody></table></div>`;}

function calendarPage(){return `${pageHead('Every road on one page','Calendar','The calendar includes WorldTour, ProSeries, U23 and selected continental racing. Filter by tier or race type; weekly simulation resolves everything that falls inside the chosen period.')}
<div class="filters"><select id="calendar-tier"><option value="all">All tiers</option>${tierOptions()}</select><select id="calendar-type"><option value="all">All types</option>${typeOptions()}</select><input id="calendar-search" placeholder="Search race…"></div><div class="calendar" id="calendar-list">${state.events.map(calendarRow).join('')}</div>`;}
function calendarRow(event){const result=currentResult(event.id),eventDay=dayOfYear(state.year,event.month,event.day),status=result?'Filed':eventDay<=state.currentDay?'Passed':'Ahead';return `<button class="event-row ${event.tier} ${status==='Filed'?'completed':''} ${state.events[state.eventIndex]?.id===event.id?'next':''}" data-open-race="${event.id}" data-tier="${event.tier}" data-type="${eventCategory(event)}" data-search="${esc(event.name.toLowerCase())}"><span class="event-date">${monthName(event.month).slice(0,3)}<br>${event.day}</span><span><strong class="event-name">${countryFlag(event.country)} ${esc(event.name)}</strong><small class="event-meta">${typeLabel(event)} · ${event.stageProfiles.length===1?STAGE_LABELS[event.stageProfiles[0]]:`${event.stageProfiles.length} stages`}</small>${result?`<small class="calendar-winner">${countryFlag(riderById(state,result.winnerId)?.nationality)} ${esc(result.winnerName)}</small>`:''}</span><span class="event-tier"><span class="chip">${tierLabel(event.tier)}</span></span><span class="event-prestige"><span class="prestige"><i style="width:${event.prestige}%"></i></span><small>Prestige ${event.prestige}</small></span><span class="chip ${status==='Filed'?'sage':status==='Ahead'?'wine':'gold'}">${status}</span></button>`;}

function racesPage(){return `${pageHead('Institutions with their own histories','Races','Every race has a permanent page: current edition, complete lineage, greatest winners, stage records, jersey records, prestige changes and status evolution.')}
<div class="filters"><select id="races-tier"><option value="all">All tiers</option>${tierOptions()}</select><select id="races-type"><option value="all">All types</option>${typeOptions()}</select><input id="races-search" placeholder="Search race…"></div><div class="race-card-grid" id="race-card-list">${[...state.events].sort((a,b)=>b.prestige-a.prestige).map(raceCard).join('')}</div>`;}
function raceCard(event){const result=currentResult(event.id),editions=event.editions?.length||0;return `<button class="race-card ${eventCategory(event)}" data-open-race="${event.id}" data-tier="${event.tier}" data-type="${eventCategory(event)}" data-search="${esc(event.name.toLowerCase())}"><div class="race-card-top"><span>${countryFlag(event.country)} <span class="chip">${tierLabel(event.tier)}</span></span><b>${event.prestige}</b></div><h3>${esc(event.name)}</h3><p>${typeLabel(event)} · ${event.stageProfiles.length===1?'One day':`${event.stageProfiles.length} stages`}</p><div class="race-card-winner"><small>${result?'Winner this year':'Current status'}</small><strong>${result?`${countryFlag(riderById(state,result.winnerId)?.nationality)} ${esc(result.winnerName)}`:'Awaiting edition'}</strong></div><footer><span>${editions} edition${editions===1?'':'s'} archived</span><span>Open →</span></footer></button>`;}
function raceDetailPage(){const event=eventById(state,selectedRaceId)||state.events[0],result=currentResult(event.id),editions=[...(event.editions||[])].reverse(),winnerCounts=countBy(editions,e=>e.winnerId,e=>({id:e.winnerId,name:e.winnerName})),stageCounts=countBy(editions.flatMap(e=>e.stageWinners||[]),s=>s.riderId,s=>({id:s.riderId,name:s.name})),jerseyEntries=editions.flatMap(e=>Object.values(e.jerseys||{}).filter(Boolean).map(id=>({id,name:riderById(state,id)?.name||id}))),jerseyCounts=countBy(jerseyEntries,x=>x.id,x=>x);
  return `${pageHead(`${tierLabel(event.tier)} · Prestige ${event.prestige}`,event.name,`${typeLabel(event)} · ${event.stageProfiles.length===1?STAGE_LABELS[event.stageProfiles[0]]:`${event.stageProfiles.length} stages`}. Race prestige and category can evolve while its lineage remains permanent.`,`<button class="btn secondary" data-route="races">← All races</button>`)}
  <div class="race-detail-banner ${eventCategory(event)}"><div><span>${monthName(event.month)} ${event.day}</span><h3>${countryFlag(event.country)} ${esc(event.name)}</h3><p>${editions.length} archived editions · Founded in the modern Chronicle era</p></div><strong>${event.prestige}</strong></div>
  ${result?resultView(result,event,false):upcomingRaceView(event)}
  <div class="grid cols-3 race-records"><section class="card"><div class="section-title flush"><h3>Most victories</h3></div>${recordList(winnerCounts,5,'wins')}</section><section class="card"><div class="section-title flush"><h3>Most stage wins</h3></div>${recordList(stageCounts,5,'stages')}</section><section class="card"><div class="section-title flush"><h3>Most jerseys</h3></div>${recordList(jerseyCounts,5,'jerseys')}</section></div>
  <div class="grid cols-2"><section class="card"><div class="section-title flush"><h3>Edition history</h3><span>${editions.length}</span></div>${editions.length?`<div class="table-wrap"><table><thead><tr><th>Year</th><th>Winner</th><th>Team</th><th>Stages</th></tr></thead><tbody>${editions.map(e=>`<tr><td>${e.year}</td><td><button class="entity-link" data-open-rider="${e.winnerId}">${countryFlag(riderById(state,e.winnerId)?.nationality)} ${esc(e.winnerName)}</button></td><td>${esc(teamName(e.teamId))}</td><td>${e.stageWinners?.length||0}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No edition has been raced yet.</p>'}</section><section class="card"><div class="section-title flush"><h3>Race evolution</h3></div>${event.history?.length?event.history.slice().reverse().map(h=>`<article class="story"><div class="story-category">${h.year}</div><h4>${h.type==='status'?`${tierLabel(h.from)} → ${tierLabel(h.to)}`:titleCase(h.type)}</h4><p>Prestige ${h.prestige||event.prestige}</p></article>`).join(''):'<p class="muted">No category or prestige changes yet.</p>'}</section></div>`;
}
function countBy(items,keyFn,valueFn){const map=new Map();for(const item of items){const key=keyFn(item);if(!key)continue;const entry=map.get(key)||{...valueFn(item),count:0};entry.count++;map.set(key,entry);}return [...map.values()].sort((a,b)=>b.count-a.count);}
function recordList(entries,limit,label){return entries.slice(0,limit).map((e,i)=>`<button class="record-row" data-open-rider="${e.id}"><span class="rank">${i+1}</span><span>${countryFlag(riderById(state,e.id)?.nationality)} <strong>${esc(e.name)}</strong></span><b>${e.count} ${label}</b></button>`).join('')||'<p class="muted">The record book is still empty.</p>';}

function ridersPage(){const riders=state.riders.filter(r=>!r.retired).sort((a,b)=>currentAbility(b)-currentAbility(a));return `${pageHead('Every generation is visible','Riders','WorldTour stars, ProSeries professionals, continental free agents and U23 prospects share one searchable career database.')}${riderFilters()}<div class="rider-grid" id="rider-list">${riders.map(riderCard).join('')}</div>`;}
function riderFilters(){return `<div class="filters"><input id="rider-search" placeholder="Search rider or country…"><select id="rider-tier"><option value="all">All tiers</option>${tierOptions()}</select><select id="rider-program"><option value="all">All race preferences</option>${PROGRAM_TYPES.map(x=>`<option value="${x}">${titleCase(x)}</option>`).join('')}</select><select id="rider-terrain"><option value="all">All stage profiles</option>${TERRAIN_TYPES.map(x=>`<option value="${x}">${titleCase(x)}</option>`).join('')}</select></div>`;}
function riderCard(r){return `<button class="rider-card" data-open-rider="${r.id}" data-tier="${r.tier}" data-program="${r.program}" data-terrain="${r.terrain}" data-search="${esc(`${r.name} ${r.nationality}`.toLowerCase())}"><div class="rating">${Math.round(currentAbility(r))}</div><div>${countryFlag(r.nationality)} <span class="rarity ${r.rarity}">${titleCase(r.rarity)}</span></div><h4>${esc(r.name)}</h4><p>${esc(teamName(r.teamId))}</p><div class="chips"><span class="chip ${r.tier==='u23'?'blue':''}">${tierLabel(r.tier)}</span><span class="chip">Age ${r.age}</span></div><div class="mini-stats"><div><strong>${r.currentSeason.raceWins}</strong><span>Races</span></div><div><strong>${r.currentSeason.stageWins}</strong><span>Stages</span></div><div><strong>${formatNumber(r.currentSeason.uciPoints)}</strong><span>Points</span></div></div><footer><span>${titleCase(r.program)}</span><span>${titleCase(r.terrain)}</span></footer></button>`;}

function teamsPage(){const rank={worldtour:4,proseries:3,u23:2,continental:1};const teams=state.teams.filter(t=>t.status==='active').sort((a,b)=>(rank[b.tier]||0)-(rank[a.tier]||0)||b.reputation-a.reputation);return `${pageHead('Organizations outlive their jerseys','Teams','The sporting organization is permanent; sponsor investment changes the visible identity, budget, attraction and recruitment power.')}
<div class="filters"><input id="team-search" placeholder="Search team or organization…"><select id="team-tier"><option value="all">All tiers</option>${tierOptions(false)}</select></div><div class="team-grid" id="team-list">${teams.map(teamCard).join('')}</div>`;}
function teamCard(t){const d=directorById(state,t.directorId);return `<button class="team-card" data-open-team="${t.id}" data-tier="${t.tier}" data-search="${esc(`${t.name} ${t.identity}`.toLowerCase())}"><div class="team-card-head"><span>${countryFlag(t.nationality)} <span class="chip ${t.tier==='worldtour'?'wine':t.tier==='u23'?'blue':'gold'}">${tierLabel(t.tier)}</span></span><strong>${t.reputation}</strong></div><h4>${esc(t.name)}</h4><p>Organization: ${esc(t.identity)}</p><div class="sponsor-band"><small>Race director</small><b>${d?`${countryFlag(d.nationality)} ${esc(d.name)}`:'Vacant'}</b></div><div class="mini-stats"><div><strong>${t.currentSeason.raceWins}</strong><span>Race wins</span></div><div><strong>${t.currentSeason.stageWins}</strong><span>Stages</span></div><div><strong>${formatNumber(t.currentSeason.uciPoints)}</strong><span>Points</span></div></div><footer><span>Budget ${t.budget}</span><span>Attraction ${t.attraction}</span></footer></button>`;}

function directorsPage(){const directors=state.directors.filter(d=>!d.retired).sort((a,b)=>b.ability-a.ability);return `${pageHead('The strategists behind the dynasties','Race Directors','Every team has one director. Agencies hold free directors, and talent can rise from a continental project to the largest teams in the world.')}
<div class="filters"><input id="director-search" placeholder="Search director…"><select id="director-tier"><option value="all">All appointments</option><option value="agency">Agencies</option>${tierOptions(false)}</select></div><div class="director-grid" id="director-list">${directors.map(directorCard).join('')}</div>`;}
function directorTier(d){return d.teamId?(teamById(state,d.teamId)?.tier||'agency'):'agency';}
function directorCard(d){const team=teamById(state,d.teamId),agency=state.directorAgencies.find(a=>a.id===d.agencyId);return `<button class="director-card" data-open-director="${d.id}" data-tier="${directorTier(d)}" data-search="${esc(`${d.name} ${team?.name||agency?.name||''}`.toLowerCase())}"><div class="rating">${d.ability}</div><div>${countryFlag(d.nationality)} <span class="rarity ${d.rarity}">${titleCase(d.rarity)}</span></div><h4>${esc(d.name)}</h4><p>${team?esc(team.name):esc(agency?.name||'Independent')}</p><div class="director-skills"><span>TAC <b>${d.tactics}</b></span><span>DEV <b>${d.development}</b></span><span>SCT <b>${d.scouting}</b></span><span>REC <b>${d.recruitment}</b></span></div><div class="mini-stats"><div><strong>${d.career.grandTours}</strong><span>Grand Tours</span></div><div><strong>${d.career.monuments}</strong><span>Monuments</span></div><div><strong>${d.career.raceWins}</strong><span>Wins</span></div></div></button>`;}

function transfersPage(){return `${pageHead('Riders, directors and sponsors move independently','The Market','Young riders can sign with any level from age 21. Directors move between teams and agencies. Sponsors can leave while the sporting organization continues.')}
<div class="grid cols-3"><section class="card"><div class="section-title flush"><h3>Rider transfers</h3></div>${marketTable(state.transfers,'rider')}</section><section class="card"><div class="section-title flush"><h3>Director appointments</h3></div>${marketTable(state.directorMoves,'director')}</section><section class="card"><div class="section-title flush"><h3>Sponsor identities</h3></div>${state.sponsorLog.length?state.sponsorLog.slice(0,60).map(change=>`<article class="story"><div class="story-category">${change.year} · ${esc(change.identity)}</div><h4>${esc(change.next)}</h4><p>${esc(change.previous)} left the jersey; the organization continued.</p></article>`).join(''):'<p class="muted">No sponsor changes yet.</p>'}</section></div>`;}
function marketTable(rows,type){if(!rows.length)return'<p class="muted">The first market opens after season one.</p>';return `<div class="market-list">${rows.slice(0,80).map(m=>`<div class="market-row"><span>${m.year}</span><button class="entity-link" data-open-${type}="${type==='rider'?m.riderId:m.directorId}">${countryFlag(type==='rider'?riderById(state,m.riderId)?.nationality:directorById(state,m.directorId)?.nationality)} ${esc(type==='rider'?m.riderName:m.directorName)}</button><small>${esc(teamName(m.from))} → ${esc(teamName(m.to))}</small></div>`).join('')}</div>`;}

function statsPage(){const rows=statRows();return `${pageHead('Compare careers across every level','Statistics','Rank riders, directors or teams by the competitions they won. Tier filters measure where the victories occurred—not simply the current category of the person or team.')}
<div class="stats-controls"><div class="tabbar entity-tabs">${['riders','directors','teams'].map(x=>`<button class="${statsEntity===x?'active':''}" data-stats-entity="${x}">${titleCase(x)}</button>`).join('')}</div><select id="stats-scope"><option value="season" ${statsScope==='season'?'selected':''}>Season ${state.year}</option><option value="career" ${statsScope==='career'?'selected':''}>All-time career</option></select><select id="stats-metric">${metricOptions()}</select><select id="stats-tier"><option value="all" ${statsTier==='all'?'selected':''}>All tiers</option>${tierOptions(true,statsTier)}</select></div>
<div class="table-wrap stats-table"><table><thead><tr><th>#</th><th>${statsEntity==='teams'?'Team':statsEntity==='directors'?'Director':'Rider'}</th><th>Current home</th><th>Career years</th><th>${metricName(statsMetric)}</th><th>Grand Tours</th><th>Monuments</th><th>Stages</th></tr></thead><tbody>${rows.slice(0,100).map((row,i)=>statsRow(row,i)).join('')}</tbody></table></div>`;}
function metricOptions(){return [['grandTours','Grand Tours won'],['monuments','Monuments won'],['weeklong','Week-long races won'],['raceWins','Total races won'],['stageWins','Stages won'],['classics','Classics won'],['championships','Championships won'],['jerseys','Jerseys won']].map(([v,l])=>`<option value="${v}" ${statsMetric===v?'selected':''}>${l}</option>`).join('');}
function metricName(metric){return {grandTours:'Grand Tours',monuments:'Monuments',weeklong:'Week-long races',raceWins:'Race wins',stageWins:'Stage wins',classics:'Classics',championships:'Championships',jerseys:'Jerseys'}[metric];}
function statRows(){const source=statsEntity==='riders'?state.riders:statsEntity==='directors'?state.directors:state.teams;return source.filter(x=>statsEntity==='teams'||x.career?.seasonCount>0||!x.retired).map(x=>{const book=statsScope==='season'?x.currentSeason:x.career;return{entity:x,book,value:statValue(book,statsMetric,statsTier)};}).sort((a,b)=>b.value-a.value||statValue(b.book,'uciPoints',statsTier)-statValue(a.book,'uciPoints',statsTier));}
function statsRow(row,index){const x=row.entity,b=row.book;if(statsEntity==='riders')return `<tr><td class="rank">${index+1}</td><td><button class="entity-link" data-open-rider="${x.id}">${countryFlag(x.nationality)} ${esc(x.name)}</button></td><td>${esc(teamName(x.teamId))}</td><td>${x.career.seasonCount}</td><td><strong>${row.value}</strong></td><td>${statValue(b,'grandTours',statsTier)}</td><td>${statValue(b,'monuments',statsTier)}</td><td>${statValue(b,'stageWins',statsTier)}</td></tr>`;if(statsEntity==='directors')return `<tr><td class="rank">${index+1}</td><td><button class="entity-link" data-open-director="${x.id}">${countryFlag(x.nationality)} ${esc(x.name)}</button></td><td>${x.teamId?esc(teamName(x.teamId)):'Agency'}</td><td>${x.career.seasonCount}</td><td><strong>${row.value}</strong></td><td>${statValue(b,'grandTours',statsTier)}</td><td>${statValue(b,'monuments',statsTier)}</td><td>${statValue(b,'stageWins',statsTier)}</td></tr>`;return `<tr><td class="rank">${index+1}</td><td><button class="entity-link" data-open-team="${x.id}">${countryFlag(x.nationality)} ${esc(x.name)}</button></td><td>${x.status==='inactive'?'Inactive':tierLabel(x.tier)}</td><td>${x.career.seasonCount}</td><td><strong>${row.value}</strong></td><td>${statValue(b,'grandTours',statsTier)}</td><td>${statValue(b,'monuments',statsTier)}</td><td>${statValue(b,'stageWins',statsTier)}</td></tr>`;}

function magazinePage(){return `${pageHead('A historical cycling annual','Le Grand Braquet','A distinctive season magazine with pre-season odds, signings and favorites; live reporting during the year; and a permanent post-season review.')}
<div class="magazine-cover"><div><span>Le Grand Braquet</span><h3>${state.year} Cycling Annual</h3><p>Routes · Rivals · Dynasties · New generations</p></div><b>${state.year}</b></div><div class="tabbar">${[['preseason','Pre-season'],['season','Current season'],['postseason','Post-season'],['archive','Archive']].map(([id,label])=>`<button class="${magazineTab===id?'active':''}" data-mag-tab="${id}">${label}</button>`).join('')}</div>${magazineContent()}`;}
function magazineContent(){if(magazineTab==='preseason')return preseasonMagazine();if(magazineTab==='postseason')return postseasonMagazine();if(magazineTab==='archive')return `<section class="card magazine-columns">${state.news.filter(n=>n.year<state.year).map(storyCard).join('')||'<p class="muted">Earlier editions will collect here.</p>'}</section>`;return `<section class="card magazine-columns">${state.news.filter(n=>n.phase==='season'&&n.year===state.year).map(storyCard).join('')||'<p class="muted">Simulate the opening weeks to publish race reports.</p>'}</section>`;}
function preseasonMagazine(){const tour=eventById(state,'tour'),giro=eventById(state,'giro'),flanders=eventById(state,'flanders'),favorites=[['Tour de France',tour],['Giro d’Italia',giro],['Tour of Flanders',flanders]].filter(x=>x[1]);return `<div class="grid cols-2"><section class="card"><div class="section-title flush"><h3>Championship odds</h3></div>${favorites.map(([name,event])=>`<article class="odds-block"><h4>${name}</h4>${eventFavorites(event,5).map((r,i)=>`<div><span>${i+1}</span><button class="entity-link" data-open-rider="${r.id}">${countryFlag(r.nationality)} ${esc(r.name)}</button><b>${Math.max(5,Math.round(42-i*7-currentAbility(r)/8))}%</b></div>`).join('')}</article>`).join('')}</section><section class="card"><div class="section-title flush"><h3>Winter signings</h3></div>${state.transfers.filter(t=>t.year===state.year).slice(0,20).map(t=>`<article class="story"><div class="story-category">${t.type==='promotion'?'Prospect promoted':'Transfer'}</div><h4>${esc(t.riderName)} joins ${esc(teamName(t.to))}</h4><p>From ${esc(teamName(t.from))}.</p></article>`).join('')||'<p class="muted">The opening universe begins before its first generated transfer window.</p>'}${state.news.filter(n=>n.phase==='preseason'&&n.year===state.year).map(storyCard).join('')}</section></div>`;}
function postseasonMagazine(){const archive=state.archives.at(-1);if(!archive)return'<article class="card"><h3>No completed season yet</h3><p class="muted">The post-season annual appears after the first year closes.</p></article>';return `<div class="grid cols-2"><section class="card"><div class="section-title flush"><h3>${archive.year} review</h3></div><article class="story lead"><div class="story-category">World number one</div><h4>${esc(archive.summary.topRider?.name||'—')}</h4><p>${archive.headline}</p></article><article class="story"><div class="story-category">Best team</div><h4>${esc(archive.summary.topTeam?.name||'—')}</h4><p>${formatNumber(archive.summary.topTeam?.points||0)} points.</p></article><article class="story"><div class="story-category">Most race wins</div><h4>${esc(archive.summary.mostWins?.name||'—')}</h4><p>${archive.summary.mostWins?.raceWins||0} victories.</p></article><article class="story"><div class="story-category">Most stage wins</div><h4>${esc(archive.summary.mostStages?.name||'—')}</h4><p>${archive.summary.mostStages?.stageWins||0} stages.</p></article></section><section class="card"><div class="section-title flush"><h3>Final top ten</h3></div>${archive.riderRanking.slice(0,10).map((r,i)=>`<div class="record-row"><span class="rank">${i+1}</span><span>${countryFlag(riderById(state,r.id)?.nationality)} <strong>${esc(r.name)}</strong><small>${esc(teamName(r.teamId))}</small></span><b>${formatNumber(r.points)}</b></div>`).join('')}</section></div>`;}
function storyCard(story){return `<article class="story ${story.importance||''}"><div class="story-category">${esc(story.category)} · ${story.year}</div><h4>${esc(story.headline)}</h4><p>${esc(story.body)}</p></article>`;}

function almanacPage(){return `${pageHead('The complete tabular archive','Almanac','The almanac is the exhaustive database: riders, teams, directors and season tables. The Hall of Fame is reserved for shorter, curated lists of greatness.')}
<div class="tabbar">${[['riders','Riders'],['teams','Teams'],['directors','Directors'],['seasons','Seasons']].map(([id,label])=>`<button class="${almanacTab===id?'active':''}" data-almanac-tab="${id}">${label}</button>`).join('')}</div>${almanacContent()}`;}
function almanacContent(){if(almanacTab==='teams')return almanacTeams();if(almanacTab==='directors')return almanacDirectors();if(almanacTab==='seasons')return almanacSeasons();return almanacRiders();}
function almanacRiders(){const riders=[...state.riders].sort((a,b)=>hallScore(b)-hallScore(a));return `<div class="table-wrap"><table><thead><tr><th>Rider</th><th>Nationality</th><th>Years</th><th>Status</th><th>Grand Tours</th><th>Monuments</th><th>Races</th><th>Stages</th><th>Points</th></tr></thead><tbody>${riders.slice(0,1000).map(r=>`<tr><td><button class="entity-link" data-open-rider="${r.id}">${countryFlag(r.nationality)} ${esc(r.name)}</button></td><td>${r.nationality}</td><td>${r.career.seasonCount}</td><td>${r.retired?'Retired':tierLabel(r.tier)}</td><td>${r.career.grandTours}</td><td>${r.career.monuments}</td><td>${r.career.raceWins}</td><td>${r.career.stageWins}</td><td>${formatNumber(r.career.uciPoints)}</td></tr>`).join('')}</tbody></table></div>`;}
function almanacTeams(){const teams=[...state.teams].sort((a,b)=>teamHallScore(b)-teamHallScore(a));return `<div class="table-wrap"><table><thead><tr><th>Organization / current sponsor</th><th>Status</th><th>Tier</th><th>Director</th><th>Seasons</th><th>Grand Tours</th><th>Monuments</th><th>Races</th><th>Stages</th></tr></thead><tbody>${teams.map(t=>`<tr><td><button class="entity-link" data-open-team="${t.id}">${countryFlag(t.nationality)} ${esc(t.name)}</button><small class="muted block">${esc(t.identity)}</small></td><td>${titleCase(t.status)}</td><td>${tierLabel(t.tier)}</td><td>${esc(directorName(t.directorId))}</td><td>${t.career.seasonCount}</td><td>${t.career.grandTours}</td><td>${t.career.monuments}</td><td>${t.career.raceWins}</td><td>${t.career.stageWins}</td></tr>`).join('')}</tbody></table></div>`;}
function almanacDirectors(){const directors=[...state.directors].sort((a,b)=>directorHallScore(b)-directorHallScore(a));return `<div class="table-wrap"><table><thead><tr><th>Director</th><th>Current appointment</th><th>Ability</th><th>Seasons</th><th>Grand Tours</th><th>Monuments</th><th>Races</th><th>Stages</th></tr></thead><tbody>${directors.map(d=>`<tr><td><button class="entity-link" data-open-director="${d.id}">${countryFlag(d.nationality)} ${esc(d.name)}</button></td><td>${d.teamId?esc(teamName(d.teamId)):d.retired?'Retired':'Agency'}</td><td>${d.ability}</td><td>${d.career.seasonCount}</td><td>${d.career.grandTours}</td><td>${d.career.monuments}</td><td>${d.career.raceWins}</td><td>${d.career.stageWins}</td></tr>`).join('')}</tbody></table></div>`;}
function almanacSeasons(){return state.archives.length?`<div class="table-wrap"><table><thead><tr><th>Year</th><th>World #1</th><th>Top team</th><th>Most wins</th><th>Most stages</th><th>Races</th></tr></thead><tbody>${[...state.archives].reverse().map(a=>`<tr><td class="rank">${a.year}</td><td>${esc(a.summary.topRider?.name||'—')}</td><td>${esc(a.summary.topTeam?.name||'—')}</td><td>${esc(a.summary.mostWins?.name||'—')} (${a.summary.mostWins?.raceWins||0})</td><td>${esc(a.summary.mostStages?.name||'—')} (${a.summary.mostStages?.stageWins||0})</td><td>${a.raceWinners.length}</td></tr>`).join('')}</tbody></table></div>`:'<article class="card"><h3>No seasons archived</h3><p class="muted">Finish the first year to open the historical table.</p></article>';}

function hallPage(){const eligible=state.riders.filter(r=>r.career.seasonCount>0||r.retired);if(!eligible.length)return `${pageHead('The short list of immortals','Hall of Fame','The Hall of Fame is a composition of short lists, not an exhaustive table.')}<article class="card"><h3>The hall opens after season one</h3><p class="muted">Greatness requires official history.</p></article>`;const top=hallOfFame(state,10),teams=[...state.teams].sort((a,b)=>teamHallScore(b)-teamHallScore(a)).slice(0,5);return `${pageHead('The short list of immortals','Hall of Fame','Weighted achievements create the overall top ten; specialist lists recognize riders whose careers were built on a particular stage profile.')}
<section class="hof-banner"><span>Greatest riders ever</span><h3>${top[0]?esc(top[0].name):'The hall awaits'}</h3><p>Grand Tours, Monuments, championships, stage wins, jerseys and longevity.</p></section>${hofRiderTable(top)}
<div class="section-title"><h3>Specialist wings</h3><span>Top five by profile</span></div><div class="grid cols-3 specialist-grid">${['rouleur','puncheur','time-trialist','climber'].map(profile=>specialistList(profile)).join('')}</div>
<div class="section-title"><h3>Greatest teams</h3><span>Top five organizations</span></div><div class="grid cols-5 hof-team-grid">${teams.map((t,i)=>`<button class="hof-team" data-open-team="${t.id}"><span class="rank">${i+1}</span>${countryFlag(t.nationality)}<h4>${esc(t.identity)}</h4><p>${t.career.grandTours} GT · ${t.career.monuments} monuments</p><strong>${formatNumber(teamHallScore(t))}</strong></button>`).join('')}</div>`;}
function hofRiderTable(riders){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Rider</th><th>Active years</th><th>Grand Tours</th><th>Monuments</th><th>Week-long</th><th>Race wins</th><th>Stages</th><th>Score</th></tr></thead><tbody>${riders.map((r,i)=>`<tr><td class="rank">${i+1}</td><td><button class="entity-link" data-open-rider="${r.id}">${countryFlag(r.nationality)} ${esc(r.name)}</button></td><td>${r.career.seasonCount}</td><td>${r.career.grandTours}</td><td>${r.career.monuments}</td><td>${r.career.weeklong}</td><td>${r.career.raceWins}</td><td>${r.career.stageWins}</td><td><strong>${formatNumber(r.hallScore)}</strong></td></tr>`).join('')}</tbody></table></div>`;}
function specialistList(profile){const riders=state.riders.filter(r=>(r.career.seasonCount>0||r.retired)&&r.terrain===profile).sort((a,b)=>hallScore(b)-hallScore(a)).slice(0,5);return `<section class="card specialist-card"><div class="profile-mark ${profile==='time-trialist'?'time-trial':profile==='rouleur'?'flat':profile==='climber'?'mountain':profile==='cobbles'?'cobbles':'hilly'}"></div><h3>${titleCase(profile)}</h3>${riders.map((r,i)=>`<button class="record-row" data-open-rider="${r.id}"><span class="rank">${i+1}</span><span>${countryFlag(r.nationality)} <strong>${esc(r.name)}</strong></span><b>${formatNumber(hallScore(r))}</b></button>`).join('')||'<p class="muted">No inductees.</p>'}</section>`;}

function settingsPage(){return `${pageHead('Archive management','Save & Settings','The simulation remains local in IndexedDB for this development version. Export the complete universe as JSON whenever you want an external backup.')}
<div class="grid cols-2"><section class="card"><h3>Current archive</h3><p><strong>${esc(state.name)}</strong><br>Drawer ${slot} · Season ${state.year} · Week ${Math.ceil(state.currentDay/7)}</p><div class="top-actions"><button class="btn" data-action="save-now">Save now</button><button class="btn secondary" data-action="export">Export JSON</button><button class="btn secondary" data-action="back-slots">Return to drawers</button></div></section><section class="card"><h3>World scale</h3><p>${state.teams.filter(t=>t.status==='active'&&t.tier==='worldtour').length} WorldTeams · ${state.teams.filter(t=>t.status==='active'&&t.tier==='proseries').length} ProTeams · ${state.teams.filter(t=>t.status==='active'&&t.tier==='u23').length} U23 programs · ${state.teams.filter(t=>t.status==='active'&&t.tier==='continental').length} lightweight continental teams.</p><p>${formatNumber(state.riders.length)} rider records · ${formatNumber(state.directors.length)} director records · ${state.events.length} races.</p><p class="muted">New universes are fully procedural. Saves created in v0.1 retain their original riders when upgraded.</p></section></div>`;}

function renderModal(){if(modal.type==='rider')return riderModal(riderById(state,modal.id));if(modal.type==='team')return teamModal(teamById(state,modal.id));if(modal.type==='director')return directorModal(directorById(state,modal.id));return'';}
function modalShell(title,body){return `<div class="modal-backdrop"><section class="modal"><header class="modal-head"><h3>${title}</h3><button data-close-modal>×</button></header><div class="modal-body">${body}</div></section></div>`;}
function riderModal(r){if(!r)return'';const targets=r.targetEvents.map(id=>eventById(state,id)).filter(Boolean),seasons=[...r.career.seasons,{year:state.year,teamId:r.teamId,teamName:teamName(r.teamId),tier:r.tier,points:r.currentSeason.uciPoints,raceWins:r.currentSeason.raceWins,stageWins:r.currentSeason.stageWins,grandTours:r.currentSeason.grandTours,monuments:r.currentSeason.monuments,weeklong:r.currentSeason.weeklong,grandTourResults:r.currentSeason.grandTourResults,current:true}].sort((a,b)=>b.year-a.year);return modalShell('Rider career dossier',`<div class="profile-hero"><div><span class="rarity ${r.rarity}">${titleCase(r.rarity)}</span><h2>${countryFlag(r.nationality)} ${esc(r.name)}</h2><p>${esc(teamName(r.teamId))} · ${tierLabel(r.tier)} · Age ${r.age}</p><div class="chips"><span class="chip wine">Race: ${titleCase(r.program)}</span><span class="chip gold">Stage: ${titleCase(r.terrain)}</span><span class="chip blue">${titleCase(r.developmentProfile)}</span></div></div><div class="profile-rating"><small>Now</small>${Math.round(currentAbility(r))}</div></div>
<div class="grid cols-4 profile-kpis"><article class="card flat kpi"><span>Potential</span><strong>${r.potential}</strong><small>Permanent talent ceiling</small></article><article class="card flat kpi"><span>Career value</span><strong>${Math.round(r.careerFactor*100)}%</strong><small>${r.age<23?'Capped at 90% before 23':`${titleCase(r.developmentProfile)} curve`}</small></article><article class="card flat kpi"><span>Career length</span><strong>${r.careerLength}</strong><small>Generated professional years</small></article><article class="card flat kpi"><span>Race days</span><strong>${r.currentSeason.raceDays}</strong><small>Fatigue ${Math.round(r.fatigue)}</small></article></div>
<div class="section-title"><h3>Career honors</h3></div><div class="honor-grid">${honor('Grand Tours',r.career.grandTours)}${honor('Monuments',r.career.monuments)}${honor('Week-long races',r.career.weeklong)}${honor('Classics',r.career.classics)}${honor('Race wins',r.career.raceWins)}${honor('Stage wins',r.career.stageWins)}${honor('Jerseys',r.career.jerseys)}${honor('World points',formatNumber(r.career.uciPoints))}</div>
<div class="grid cols-2"><section class="card flat"><div class="section-title flush"><h3>Stages by profile</h3></div>${stageProfileBreakdown(r.career.stageWinsByProfile)}</section><section class="card flat"><div class="section-title flush"><h3>${state.year} targets</h3></div><div class="chips">${targets.map(e=>`<span class="chip">${esc(e.name)}</span>`).join('')||'<span class="muted">No major targets.</span>'}</div><p><strong>${r.currentSeason.raceWins}</strong> races · <strong>${r.currentSeason.stageWins}</strong> stages · <strong>${formatNumber(r.currentSeason.uciPoints)}</strong> points this year.</p></section></div>
<div class="section-title"><h3>Year-by-year career</h3></div><div class="table-wrap"><table><thead><tr><th>Year</th><th>Team</th><th>Category</th><th>Points</th><th>Races</th><th>Stages</th><th>Grand Tours</th><th>Major honors</th></tr></thead><tbody>${seasons.map(s=>`<tr class="${s.current?'current-row':''}"><td>${s.year}${s.current?' *':''}</td><td>${esc(s.teamName||teamName(s.teamId))}</td><td>${tierLabel(s.tier)}</td><td>${formatNumber(s.points)}</td><td>${s.raceWins||0}</td><td>${s.stageWins||0}</td><td>${(s.grandTourResults||[]).map(g=>`${g.event.replace(/(Tour de France|Giro d’Italia|La Vuelta a España)/,m=>m)} #${g.rank}`).join(' · ')||'—'}</td><td>${s.grandTours||0} GT · ${s.monuments||0} monuments · ${s.weeklong||0} week-long</td></tr>`).join('')}</tbody></table></div>
<div class="section-title"><h3>Best recorded results</h3><span>Hall score ${formatNumber(hallScore(r))}</span></div>${r.career.results.length?`<div class="table-wrap"><table><thead><tr><th>Year</th><th>Race</th><th>Tier</th><th>Place</th></tr></thead><tbody>${[...r.career.results].reverse().slice(0,40).map(x=>`<tr><td>${x.year}</td><td><button class="entity-link" data-open-race="${x.eventId}">${esc(x.event)}</button></td><td>${tierLabel(x.tier)}</td><td>${x.rank}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No top-five result yet.</p>'}`);}
function honor(label,value){return `<div><span>${label}</span><strong>${value}</strong></div>`;}
function stageProfileBreakdown(values){const max=Math.max(1,...Object.values(values||{}));return Object.entries(values||{}).map(([profile,value])=>`<div class="profile-stat"><span class="profile-mark ${profile}">${STAGE_LABELS[profile]}</span><i><b style="width:${value/max*100}%"></b></i><strong>${value}</strong></div>`).join('');}
function teamModal(t){if(!t)return'';const roster=t.roster.map(id=>riderById(state,id)).filter(Boolean).sort((a,b)=>currentAbility(b)-currentAbility(a)),d=directorById(state,t.directorId);return modalShell('Team organization & lineage',`<div class="profile-hero"><div><span class="chip ${t.tier==='worldtour'?'wine':t.tier==='u23'?'blue':'gold'}">${tierLabel(t.tier)}</span><h2>${countryFlag(t.nationality)} ${esc(t.name)}</h2><p>Permanent organization: <strong>${esc(t.identity)}</strong> · ${t.status==='active'?tierLabel(t.tier):'Inactive organization'}</p><p>Race director: ${d?`<button class="entity-link" data-open-director="${d.id}">${countryFlag(d.nationality)} ${esc(d.name)}</button>`:'Vacant'}</p></div><div class="profile-rating"><small>Rep.</small>${t.reputation}</div></div>
<div class="grid cols-4 profile-kpis">${honorCard('Budget',t.budget,'Sponsor investment')}${honorCard('Attraction',t.attraction,'Recruitment power')}${honorCard('Season points',formatNumber(t.currentSeason.uciPoints),`${t.currentSeason.raceWins} race wins`)}${honorCard('Sponsor ends',t.sponsor?.expires||'—',t.sponsor?.name||'No title sponsor')}</div>
<div class="section-title"><h3>Organization honors</h3></div><div class="honor-grid">${honor('Grand Tours',t.career.grandTours)}${honor('Monuments',t.career.monuments)}${honor('Week-long races',t.career.weeklong)}${honor('Classics',t.career.classics)}${honor('Race wins',t.career.raceWins)}${honor('Stage wins',t.career.stageWins)}${honor('Jerseys',t.career.jerseys)}${honor('Hall score',formatNumber(teamHallScore(t)))}</div>
<div class="grid cols-2"><section class="card flat"><div class="section-title flush"><h3>Sponsor history</h3></div>${t.history.filter(x=>x.type==='sponsor').slice().reverse().map(x=>`<article class="story"><div class="story-category">${x.year}</div><h4>${esc(x.name)}</h4>${x.previous?`<p>Replaced ${esc(x.previous)}.</p>`:''}</article>`).join('')}</section><section class="card flat"><div class="section-title flush"><h3>Season history</h3></div><div class="table-wrap"><table><thead><tr><th>Year</th><th>Name</th><th>Tier</th><th>Races</th><th>Stages</th><th>GT</th><th>Mon.</th></tr></thead><tbody>${[...t.career.seasons].reverse().map(s=>`<tr><td>${s.year}</td><td>${esc(s.name)}</td><td>${tierLabel(s.tier)}</td><td>${s.raceWins}</td><td>${s.stageWins}</td><td>${s.grandTours}</td><td>${s.monuments}</td></tr>`).join('')}</tbody></table></div></section></div>
<div class="section-title"><h3>Current roster</h3><span>${roster.length} riders</span></div><div class="table-wrap"><table><thead><tr><th>Rider</th><th>Age</th><th>Role</th><th>Race preference</th><th>Stage profile</th><th>Now</th><th>Potential</th></tr></thead><tbody>${roster.map(r=>`<tr><td><button class="entity-link" data-open-rider="${r.id}">${countryFlag(r.nationality)} ${esc(r.name)}</button></td><td>${r.age}</td><td>${r.role}</td><td>${titleCase(r.program)}</td><td>${titleCase(r.terrain)}</td><td>${Math.round(currentAbility(r))}</td><td>${r.potential}</td></tr>`).join('')}</tbody></table></div>`);}
function honorCard(label,value,small){return `<article class="card flat kpi"><span>${label}</span><strong>${value}</strong><small>${esc(small)}</small></article>`;}
function directorModal(d){if(!d)return'';const team=teamById(state,d.teamId),agency=state.directorAgencies.find(a=>a.id===d.agencyId);return modalShell('Race director dossier',`<div class="profile-hero"><div><span class="rarity ${d.rarity}">${titleCase(d.rarity)}</span><h2>${countryFlag(d.nationality)} ${esc(d.name)}</h2><p>${team?esc(team.name):d.retired?'Retired':esc(agency?.name||'Agency market')} · Age ${d.age}</p></div><div class="profile-rating"><small>Ability</small>${d.ability}</div></div>
<div class="director-skills large"><span>Tactics <b>${d.tactics}</b></span><span>Development <b>${d.development}</b></span><span>Scouting <b>${d.scouting}</b></span><span>Recruitment <b>${d.recruitment}</b></span></div>
<div class="section-title"><h3>Career honors</h3></div><div class="honor-grid">${honor('Grand Tours',d.career.grandTours)}${honor('Monuments',d.career.monuments)}${honor('Week-long races',d.career.weeklong)}${honor('Race wins',d.career.raceWins)}${honor('Stage wins',d.career.stageWins)}${honor('Jerseys',d.career.jerseys)}${honor('Seasons',d.career.seasonCount)}${honor('Hall score',formatNumber(directorHallScore(d)))}</div>
<div class="section-title"><h3>Year-by-year appointments</h3></div><div class="table-wrap"><table><thead><tr><th>Year</th><th>Team</th><th>Tier</th><th>Points</th><th>Races</th><th>Stages</th><th>Grand Tours</th><th>Monuments</th></tr></thead><tbody>${[...d.career.seasons].reverse().map(s=>`<tr><td>${s.year}</td><td>${esc(s.teamName||teamName(s.teamId))}</td><td>${tierLabel(s.tier)}</td><td>${formatNumber(s.points)}</td><td>${s.raceWins}</td><td>${s.stageWins}</td><td>${s.grandTours}</td><td>${s.monuments}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h3>Career log</h3></div>${[...d.history].reverse().map(h=>`<article class="story"><div class="story-category">${h.year}</div><h4>${esc(h.text)}</h4></article>`).join('')}`);}

function tierOptions(includeNational=true,selected=''){return [['worldtour','WorldTour'],['proseries','ProSeries'],['continental','Continental'],['u23','U23'],...(includeNational?[['national','Championships']]:[])].map(([v,l])=>`<option value="${v}" ${selected===v?'selected':''}>${l}</option>`).join('');}
function typeOptions(){return [['grand-tour','Grand Tours'],['monument','Monuments'],['stage-race','Stage races'],['classic','Classics'],['championship','Championships']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('');}
function eventFavorites(event,limit=5){return state.riders.filter(r=>!r.retired&&r.targetEvents.includes(event.id)&&((event.tier==='u23'&&r.age<=22)||(event.tier!=='u23'))).sort((a,b)=>currentAbility(b)-currentAbility(a)).slice(0,limit);}

if(app){
app.addEventListener('click',async event=>{
  const target=event.target.closest('button,[data-route],[data-open-rider],[data-open-team],[data-open-director],[data-open-race],[data-close-modal]');if(!target)return;
  if(target.dataset.loadSlot){await openSlot(Number(target.dataset.loadSlot));return;}if(target.dataset.newSlot){await newSlot(Number(target.dataset.newSlot));return;}if(target.dataset.deleteSlot){if(confirm('Delete this entire cycling universe?')){await deleteUniverse(Number(target.dataset.deleteSlot));renderSaveScreen(await listUniverses());}return;}
  if(target.dataset.route){route=target.dataset.route;modal=null;render();return;}if(target.dataset.menu!==undefined){document.querySelector('#sidebar')?.classList.toggle('open');return;}
  if(target.dataset.selectResult){selectedEventId=target.dataset.selectResult;render();return;}if(target.dataset.openRace){selectedRaceId=target.dataset.openRace;route='race-detail';modal=null;render();return;}
  if(target.dataset.openRider){modal={type:'rider',id:target.dataset.openRider};render();return;}if(target.dataset.openTeam){modal={type:'team',id:target.dataset.openTeam};render();return;}if(target.dataset.openDirector){modal={type:'director',id:target.dataset.openDirector};render();return;}if(target.dataset.closeModal!==undefined){modal=null;render();return;}
  if(target.dataset.magTab){magazineTab=target.dataset.magTab;render();return;}if(target.dataset.almanacTab){almanacTab=target.dataset.almanacTab;render();return;}if(target.dataset.statsEntity){statsEntity=target.dataset.statsEntity;render();return;}
  const action=target.dataset.action;if(!action||busy)return;
  if(action==='simulate-1'||action==='simulate-4'){busy=true;const weeks=action==='simulate-1'?1:4,year=state.year;const output=simulateWeeks(state,weeks);if(output.results.length)selectedEventId=output.results.at(-1).eventId;await persist();busy=false;route='results';render();toast(output.seasonComplete?`Season ${year} completed and archived.`:`${weeks} week${weeks===1?'':'s'} simulated · ${output.results.length} race${output.results.length===1?'':'s'} completed.`);}
  if(action==='simulate-season'){if(!confirm(`Simulate the remainder of ${state.year}?`))return;busy=true;renderLoading();const year=state.year,output=simulateSeason(state);await persist();busy=false;route='results';selectedEventId=state.events[0]?.id;render();toast(`Season ${year} completed · ${output.results.length} races resolved.`);}
  if(action==='save-now'){await persist();toast('Chronicle saved.');}if(action==='back-slots'){await persist();state=null;slot=null;renderSaveScreen(await listUniverses());}if(action==='export'){const blob=new Blob([JSON.stringify(state)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`peloton-chronicle-${state.year}.json`;anchor.click();URL.revokeObjectURL(url);}
});
app.addEventListener('click',event=>{if(event.target.classList.contains('modal-backdrop')){modal=null;render();}});
app.addEventListener('input',event=>{const id=event.target.id;if(id.startsWith('results-'))filterGroup('results-list','race-index-row','results');if(id.startsWith('calendar-'))filterGroup('calendar-list','event-row','calendar');if(id.startsWith('races-'))filterGroup('race-card-list','race-card','races');if(id.startsWith('rider-'))filterPeople('rider');if(id.startsWith('team-'))filterPeople('team');if(id.startsWith('director-'))filterPeople('director');});
app.addEventListener('change',event=>{const id=event.target.id;if(id.startsWith('results-'))filterGroup('results-list','race-index-row','results');if(id.startsWith('calendar-'))filterGroup('calendar-list','event-row','calendar');if(id.startsWith('races-'))filterGroup('race-card-list','race-card','races');if(id.startsWith('rider-'))filterPeople('rider');if(id.startsWith('team-'))filterPeople('team');if(id.startsWith('director-'))filterPeople('director');if(id==='stats-scope'){statsScope=event.target.value;render();}if(id==='stats-metric'){statsMetric=event.target.value;render();}if(id==='stats-tier'){statsTier=event.target.value;render();}});
}
function filterGroup(containerId,itemClass,prefix){const tier=document.querySelector(`#${prefix}-tier`)?.value||'all',type=document.querySelector(`#${prefix}-type`)?.value||'all',q=document.querySelector(`#${prefix}-search`)?.value.toLowerCase()||'';document.querySelectorAll(`#${containerId} .${itemClass}`).forEach(row=>row.hidden=!((tier==='all'||row.dataset.tier===tier)&&(type==='all'||row.dataset.type===type)&&(row.dataset.search||'').includes(q)));}
function filterPeople(type){const q=document.querySelector(`#${type}-search`)?.value.toLowerCase()||'',tier=document.querySelector(`#${type}-tier`)?.value||'all',program=document.querySelector('#rider-program')?.value||'all',terrain=document.querySelector('#rider-terrain')?.value||'all',selector=type==='rider'?'.rider-card':type==='team'?'.team-card':'.director-card';document.querySelectorAll(selector).forEach(card=>card.hidden=!((card.dataset.search||'').includes(q)&&(tier==='all'||card.dataset.tier===tier)&&(type!=='rider'||program==='all'||card.dataset.program===program)&&(type!=='rider'||terrain==='all'||card.dataset.terrain===terrain)));}
